networks:
  default:
    name: lumina
    external: true
services:
  fivem:
    restart: "${RESTART_POLICY:-no}"
    network_mode: "bridge"
    ports:
      - 30120:30120
      - 40120:40120

  mariadb:
    restart: "${RESTART_POLICY:-no}"
    network_mode: "bridge"
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
